# Used at project startup ----------------------------------------------------------------------------------
version: '3.9'
services:
  composer:
    container_name: composer
    build:
      context: .
    volumes:
      - ./src:/app
# ----------------------------------------------------------------------------------------------------------

# Used when building the project ---------------------------------------------------------------------------
# version: '3.9'
# services:
#   application:
#     container_name: ${APP_NAME}_app
#     build:
#       context: .
#     ports:
#       - 80:8000
#     volumes:
#       - ./src:/app
#     depends_on:
#       - database

#   database:
#     image: docker.io/mysql
#     container_name: ${APP_NAME}_mysql
#     ports:
#         - 3306:3306
#     environment:
#         MYSQL_DATABASE: ${APP_NAME}_db
#         MYSQL_USER: ${APP_NAME}_admin
#         MYSQL_PASSWORD: password
#         MYSQL_ROOT_PASSWORD: password

#   remote_database:
#     image: docker.io/phpmyadmin
#     container_name: ${APP_NAME}_php_myadmin
#     ports:
#         - 8080:80
#     links:
#         - database
#     environment:
#         PMA_HOST: database
#         PMA_PORT: 3306
#         PMA_ARBITRARY: 1
#     depends_on:
#         - database
# ----------------------------------------------------------------------------------------------------------
