networks:
  surface_network:

services:
  database:
    image: mysql
    container_name: ${APP_NAME}_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${APP_NAME}_db
      MYSQL_USER: ${APP_NAME}_admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - surface_network

  remote_database:
    image: phpmyadmin
    container_name: ${APP_NAME}_php_myadmin
    ports:
        - 8080:80
    links:
        - database
    environment:
        PMA_HOST: database
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
    networks:
      - surface_network
    depends_on:
      - database

  application:
    container_name: ${APP_NAME}_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./src/:/var/www/html
    networks:
      - surface_network
    depends_on:
      - database

  server:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - surface_network
    depends_on:
      - application
